project:
  type: website
  output-dir: ../../docs/py

website:
  title: "querychat"
  site-url: https://posit-dev.github.io/querychat/py
  description: Chat with your data in Shiny apps

  bread-crumbs: true
  open-graph: true
  twitter-card: true

  repo-url: https://github.com/posit-dev/querychat/
  repo-actions: [issue, edit]
  repo-subdir: pkg-py/docs

  page-footer:
    left: |
      Proudly supported by
      [![](https://posit.co/wp-content/uploads/2024/06/Posit-Logos-2024_horiz-full-color.svg){fig-alt="Posit" width=65px}](https://posit.co)

  navbar:
    left:
      - text: Get Started
        href: index.qmd
      - text: "Examples"
        href: examples/index.qmd
      - text: API Reference
        href: reference/index.qmd

    tools:
      - icon: github
        menu:
          - text: Source code
            href:  https://github.com/posit-dev/querychat/tree/main/pkg-py
          - text: Report a bug
            href:  https://github.com/posit-dev/querychat/issues/new


  sidebar:
    - id: examples
      title: "Examples"
      style: docked
      type: light
      background: light
      foreground: dark
      contents:
      - href: examples/index.qmd
      - section: "DataFrames"
        contents:
          - href: examples/pandas.qmd
      - section: "Databases"
        contents:
          - href: examples/sqlite.qmd

format:
  html:
    theme: [brand]
    highlight-style: github
    toc: true

lightbox: auto

metadata-files:
  - reference/_sidebar.yml

quartodoc:
  package: querychat
  render_interlinks: true
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css
  sections:
    - title: Get Started
      desc: The basic building blocks of Querychat
      contents:
        - init
        - sidebar
        - server

    - title: Customize
      desc: Dive deeper into customizing Querychat
      contents:
        - ui
        - system_prompt

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    pydantic:
      url: https://docs.pydantic.dev/latest/
    python:
      url: https://docs.python.org/3/

editor:
  render-on-save: true
  markdown:
    canonical: true
    wrap: sentence
