project:
  type: website
  output-dir: ../../docs/py
  pre-render:
    cp ../CHANGELOG.md CHANGELOG.md

website:
  title: "querychat"
  site-url: https://posit-dev.github.io/querychat/py
  description: Explore data using natural language
  page-navigation: true

  bread-crumbs: true
  open-graph: true
  twitter-card: true

  repo-url: https://github.com/posit-dev/querychat/
  repo-actions: [issue, edit]
  repo-subdir: pkg-py/docs

  page-footer:
    left: |
      Proudly supported by
      [![](https://posit.co/wp-content/uploads/2024/06/Posit-Logos-2024_horiz-full-color.svg){fig-alt="Posit" width=65px}](https://posit.co)

  navbar:
    background: "#193D56"
    search: true
    title: '<span class="ms-3 fs-3 lead" style="vertical-align:middle;">QueryChat</span>'
    #title: '<img src="/images/querychat.png" height="40px" alt="querychat website"/><span class="ms-3 fs-3 lead header text-white" style="vertical-align:middle;">QueryChat</span>'

    right:
      - text: API Reference
        href: reference/index.qmd
      - text: Changelog
        href: /CHANGELOG.html
      - icon: github
        href: https://github.com/posit-dev/querychat
        aria-label: GitHub repository

  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - index.qmd
        - section: "Overview"
          contents:
            - models.qmd
            - data-sources.qmd
            - context.qmd
            - build.qmd
            - greet.qmd
            - tools.qmd


format:
  html:
    theme:
      - styles.scss
    toc: true

lightbox: auto

metadata-files:
  - reference/_sidebar.yml

quartodoc:
  package: querychat
  render_interlinks: true
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css
  sections:
    - title: The QueryChat class
      desc: The starting point for any QueryChat session
      contents:
        - name: QueryChat
          include_inherited: true
        - name: express.QueryChat
          include_inherited: true

    - title: Reactive values
      desc: Session-specific reactive values representing the current query
      contents:
        - types.ServerValues

    - title: Data Sources
      desc: The underlying logic for managing data sources
      contents:
        - name: types.DataSource
          signature_name: short
        - name: types.DataFrameSource
          signature_name: short
        - name: types.SQLAlchemySource
          signature_name: short

    - title: Tools
      desc: The underlying tools provided to the LLM
      contents:
        - name: tools.tool_query
          signature_name: short
        - name: tools.tool_update_dashboard
          signature_name: short
        - name: tools.tool_reset_dashboard
          signature_name: short

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    pydantic:
      url: https://docs.pydantic.dev/latest/
    python:
      url: https://docs.python.org/3/

editor:
  render-on-save: true
  markdown:
    canonical: true
    wrap: sentence
