name: Python - Release

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.12

jobs:
  pypi-release:
    name: Build and release Python package
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/py-v')

    environment:
      name: pypi
      url: https://pypi.org/project/querychat/

    permissions: # for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: ğŸš€ Install uv
        uses: astral-sh/setup-uv@v3

      - name: ğŸ Set up Python ${{ env.PYTHON_VERSION }}
        working-directory: ./pkg-py
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: ğŸ“¦ Install the project
        working-directory: ./pkg-py
        run: uv sync --python ${{ env.PYTHON_VERSION }} --all-extras

      #   - name: ğŸ§ª Check tests
      #     working-directory: ./pkg-py
      #     run: make check-tests

      - name: ğŸ“ Check types
        working-directory: ./pkg-py
        run: make check-types

      - name: ğŸ“ Check formatting
        working-directory: ./pkg-py
        run: make check-format

      - name: ğŸ§³ Build package
        working-directory: ./pkg-py
        run: make build

      # TODO: https://pypi.org/manage/project/querychat/settings/publishing/
      - name: ğŸš¢ Publish release on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./pkg-py/dist
